---
#
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

    - name: Add Etage key
      apt_key: url=http://repo.etagecom.io/pubkey.gpg state=present
    - name: Add Etage dev repo
      apt_repository: repo='deb http://repo.etagecom.io {{ item }} main' update_cache=no mode=664
      with_items:
          - dev
          - test
          - beta
          - stable

    - name: Add Endaga key
      apt_key: url=http://repo.endaga.com/pubkey.gpg state=present
    - name: Add Endaga repo
      apt_repository: repo='deb http://repo.endaga.com dev main' update_cache=no mode=664

    - name: Set repo.endaga to order 10
      shell: sudo mv /etc/apt/sources.list.d/repo_endaga_com.list /etc/apt/sources.list.d/10_repo_endaga_com.list || exit 0

    - name: Set repo.etagecom to order 20
      shell: sudo mv /etc/apt/sources.list.d/repo_etagecom_io.list /etc/apt/sources.list.d/20_repo_etagecom_io.list || exit 0
